spring:
  application:
    name: oss-prototype
  kafka:
    bootstrap-servers: 115.145.179.193:15001
    producer:
      topic: request
    consumer:
      group-id: oss-prototype
      topic: result
  redis:
    host: 115.145.179.193
    port: 15002
    password: CqpBB9pmZo
  data:
    mongodb:
      host: localhost
      port: 27017
      database: oss-prototype
server:
  port: 15003
# monitoring
management:
  endpoint:
    shutdown:
      enabled: true
    web:
      exposure:
        include: health, info, shutdown
