spring:
  application:
    name: oss-prototype
  kafka:
    bootstrap-servers: 192.168.49.2:30789
    producer:
      topic: request
    consumer:
      group-id: oss-prototype
      topic: result
  redis:
    host: localhost
    port: 6379
    password: XouW7bQfyD
  data:
    mongodb:
      uri: mongodb://oss-user:oss-user1!@192.168.49.2:30017,192.168.49.2:30018/oss
# monitoring
management:
  endpoint:
    shutdown:
      enabled: true
    web:
      exposure:
        include: health, info, shutdown
