spring:
  application:
    name: oss-prototype
  kafka:
    bootstrap-servers: 192.168.49.2:30165
    producer:
      topic: request
    consumer:
      group-id: oss-prototype
      topic: result
  redis:
    host: localhost
    port: 6379
    password: y6SNhEUeEQ
  mongodb:
    host: localhost
    port: 27017
    database: oss-prototype
management:
  endpoint:
    shutdown:
      enabled: true
    web:
      exposure:
        include: health, info, shutdown
