spring:
  application:
    name: oss-prototype
  kafka:
    bootstrap-servers: 192.168.49.2:30789
    producer:
      topic: request
    consumer:
      group-id: oss-prototype
      topic: result
  redis:
    host: localhost
    port: 6379
    password: XouW7bQfyD
  data:
    mongodb:
      host: 192.168.49.2
      port: 30017
      database: oss
#      username: oss-root
#      password: oss-root1!
      username: oss-user
      password: oss-user1!
# monitoring
management:
  endpoint:
    shutdown:
      enabled: true
    web:
      exposure:
        include: health, info, shutdown
