spring:
  application:
    name: oss-prototype
  kafka:
    # bootstrap-servers: 115.145.179.193:15001
    bootstrap-servers: comnet.skku.ac.kr:15001
    producer:
      topic: request
    consumer:
      group-id: oss-prototype
      topic: result
  redis:
    host: comnet.skku.ac.kr
    port: 15002
    password: CqpBB9pmZo
management:
  endpoint:
    shutdown:
      enabled: true
    web:
      exposure:
        include: health, info, shutdown
